### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by SiriusDreamz** [PhaseEvolution/RampTimerBuilder#1]
Found an error.

Description:
When clicking the minus icon next to the drop down menu in the section "Presets and Saved Programs" the program throws an error. See details below. I suspect that since there was no preset saved when I clicked, an object or variable is not existing/null.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at RampTimerBuilder.frmMain.btnDeletePreset_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by PhaseEvolution** [comment]
Thanks. I will look into that.

**Comment by PhaseEvolution** [comment]
This has been resolved in the latest push to github.
